image: nodejs
branches:
  - master
  - dev
matrix:
  - env: SCRIPT=lint
  - env: SCRIPT=test:coverage
install:
  - npm ci
script:
  - npm run $SCRIPT
deploy:
  - npm ci
  - npm run build
  - tar -czvf dist.tar.gz -C build .
  - /home/abstruse/deploy.sh "KeecoHub-$ABSTRUSE_BRANCH" "KeecoHub" dist.tar.gz
  - sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWD
  - sudo docker build -t "keeco/keeco-hub:$(if [ "$ABSTRUSE_BRANCH" == "master" ]; then echo "latest"; else echo $ABSTRUSE_BRANCH | sed -r 's/\//_/g'; fi)" .
  - sudo docker push "keeco/keeco-hub:$(if [ "$ABSTRUSE_BRANCH" == "master" ]; then echo "latest"; else echo $ABSTRUSE_BRANCH | sed -r 's/\//_/g'; fi)"
  - sudo docker logout